/**
 *
 * Register all const for action types
 *
 */
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const FETCH_POSTS_COMMENT_REQUEST = 'FETCH_POSTS_COMMENT_REQUEST'
export const FETCH_POSTS_COMMENT_SUCCESS = 'FETCH_POSTS_COMMENT_SUCCESS'
export const FETCH_POSTS_COMMENT_FAILURE = 'FETCH_POSTS_COMMENT_FAILURE'
